"""Independent braid-group checks for prop:qt-equivariance."""

from __future__ import annotations

from compute.lib.independent_verification import independent_verification


def _b3_positive_equivalent(word_a, word_b):
    """Equivalence in the positive B3 monoid generated by s1 s2 s1 = s2 s1 s2."""
    rewrites = {
        (1, 2, 1): (2, 1, 2),
        (2, 1, 2): (1, 2, 1),
    }
    seen = {tuple(word_a)}
    frontier = [tuple(word_a)]
    target = tuple(word_b)
    while frontier:
        word = frontier.pop()
        if word == target:
            return True
        for i in range(max(0, len(word) - 2)):
            chunk = word[i : i + 3]
            if chunk in rewrites:
                new_word = word[:i] + rewrites[chunk] + word[i + 3 :]
                if new_word not in seen:
                    seen.add(new_word)
                    frontier.append(new_word)
    return False


@independent_verification(
    claim="prop:qt-equivariance",
    derived_from=["Braided annular clutching criterion in 3d_gravity.tex"],
    verified_against=[
        "Artin 1925 braid group presentation",
        "Matsumoto 1964 reduced-word theorem for Coxeter groups",
        "Joyal-Street 1993 braided tensor categories",
    ],
    disjoint_rationale=(
        "The check uses only braid-group presentations and the Coxeter "
        "reduced-word theorem.  It is independent of the programme's "
        "annular-bar construction and verifies the exact logical gap: "
        "YBE gives braid coherence, but symmetric graph equivariance needs "
        "pure-braid descent and inverse-orientation data."
    ),
)
def test_ybe_gives_braid_coherence_not_symmetric_descent():
    """Braid relations identify reduced words but do not impose s_i^2=1."""
    assert _b3_positive_equivalent((1, 2, 1), (2, 1, 2))

    # The Artin braid generator maps to a transposition in S_2, but the
    # braid group keeps sigma^2 as a nontrivial pure braid.  Thus YBE/braid
    # coherence alone cannot be an ordinary symmetric-group action.
    b2_identity = 0
    b2_sigma = 1
    b2_pure = b2_sigma + b2_sigma
    assert b2_pure != b2_identity

    # Reversing an annular seam uses the inverse braid.  It is not equal to
    # the positive braid unless a separate triangular/symmetric descent
    # relation is supplied.
    b2_sigma_inverse = -1
    assert b2_sigma_inverse != b2_sigma
